---
title: "sprinters"
author: "Audrey Bertin"
date: "8/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(tidyverse)
library(ggthemes)
library(gghighlight)
```

# Scrape data from worldathletics.org on top 100 female 100m times

```{r}
# Connect to site
page_100m <- "https://www.worldathletics.org/records/all-time-toplists/sprints/100-metres/outdoor/women/senior?page=1"

top_100m <- read_html(page_100m)
```


```{r}
# Pull results

results_100m <- top_100m %>% 
  html_nodes(xpath = '//*[@id="toplists"]/div[3]/table') %>%
  html_table()

records_100m <- results_100m[[1]] %>%
  select(Rank, Mark, Competitor, Nat, Venue, Date)
```

# Get 200m times

```{r}
# Connect to site

page_200m <- "https://www.worldathletics.org/records/all-time-toplists/sprints/200-metres/outdoor/women/senior?regionType=world&timing=electronic&windReading=regular&page=1&bestResultsOnly=true&firstDay=1899-12-31&lastDay=2021-08-14"

top_200m <- read_html(page_200m)
```

```{r}
# Pull data

results_200m <- top_200m %>% 
  html_nodes(xpath = '//*[@id="toplists"]/div[3]/table') %>%
  html_table()

records_200m <- results_200m[[1]] %>%
  select(Rank, Mark, Competitor, Nat, Venue, Date)
```

# Join Data

```{r}
records_100m <- records_100m %>%
  mutate(Distance = rep("100m", 100))

records_200m <- records_200m %>%
  mutate(Distance = rep("200m", 100))

```

```{r}
combined_records <- rbind(records_100m, records_200m)
```

# Extract Year

```{r}
combined_records <- combined_records %>% 
  mutate(Year = as.numeric(str_sub(Date, -5, -1)))
```

# Graph

```{r}
ggplot(combined_records %>% filter(Distance == "100m"), aes(x = Year, y = Mark)) +
  geom_point(color = "#00a32f", size = 3) +
  theme_fivethirtyeight() +
  scale_x_continuous(
    breaks = c(1960, 1965, 1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020),
    labels = c("'60", "'65", "'70", "'75", "'80", "'85", "'90", "'95", "'00", "'05", "'10", "'15", "'20")) +
  gghighlight(Nat =="JAM") +
  ggtitle("The Fastest Women in the World - 100m",
          subtitle = "Top 100 Times in History, Jamaican Records Highlighted Green") +
  theme(axis.title.x = element_text(),
        axis.title.y = element_text()) +
  xlab("Year") +
  ylab("Time")
  
```


```{r}
ggplot(combined_records %>% filter(Distance == "200m", Year > 1980), aes(x = Year, y = Mark)) +
  geom_point(color = "#00a32f", size = 3) +
  theme_fivethirtyeight() +
  scale_x_continuous(
    breaks = c(1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020),
    labels = c( "'85", "'90", "'95", "'00", "'05", "'10", "'15", "'20")) +
  gghighlight(Nat =="JAM") +
  ggtitle("The Fastest Women in the World - 200m",
          subtitle = "Top 100 Times in History, Jamaican Records Highlighted Green") +
  theme(axis.title.x = element_text(),
        axis.title.y = element_text()) +
  xlab("Year") +
  ylab("Time")
```

# Get Olympic Medal Results By Country

Note that these only go through 2016!!

```{r}
olympics <- readr::read_csv("data/olympics/athlete_events.csv")
```

```{r}
olympic_sprinters <- olympics %>% filter(Sport == "Athletics",
                             Event %in% c("Athletics Women's 100 metres", 
                                          "Athletics Women's 200 metres"))
```

```{r}
table <- olympic_sprinters %>%
  group_by(Team) %>%
  summarize(Gold = sum(Medal == "Gold", na.rm = TRUE),
            Silver = sum(Medal == "Silver", na.rm = TRUE),
            Bronze = sum(Medal == "Bronze", na.rm = TRUE),
            Total = Gold + Silver + Bronze) %>%
  arrange(desc(Total)) %>%
  head(10)
```

```{r}
library(formattable)
```

```{r}
formattable(table, 
            align =c("l","c","c","c","c"),
            list(`Gold` = formatter(
              "span", style = ~ style(color = "goldenrod",font.weight = "bold")),
              `Silver` = formatter(
              "span", style = ~ style(color = "grey",font.weight = "bold")),
              `Bronze` = formatter(
              "span", style = ~ style(color = "brown",font.weight = "bold")),
              `Total` = formatter(
              "span", style = ~ style(color = "green",font.weight = "bold"))
))

```

