---
title: "ufc"
author: "Audrey Bertin"
date: "7/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggthemes)
```

```{r}
#fights_raw <- readr::read_delim("data/ufc/raw_total_fight_data.csv", delim = ";")
fighter <- readr::read_csv("data/ufc/raw_fighter_details.csv")

fights <- readr::read_csv("data/ufc/data.csv")
#preprocessed <- readr::read_csv("data/ufc/preprocessed_data.csv")
```

# Data Prep

```{r}
fighters_clean <- fighters %>%
  separate(Height, into = c("ft", "inch"), sep = " ") %>%
  mutate(ft = as.numeric(stringr::str_sub(ft, end = -2)),
         inch = as.numeric(stringr::str_sub(inch, end = -2)),
         Height = (ft * 12) + inch,
         Weight = as.numeric(stringr::str_sub(Weight, end = -6)),
         Reach = as.numeric(stringr::str_sub(Reach, end = -2)),
         Str_Acc = as.numeric(stringr::str_sub(Str_Acc, end = -2)),
         Str_Def = as.numeric(stringr::str_sub(Str_Def, end = -2)),
         TD_Acc = as.numeric(stringr::str_sub(TD_Acc, end = -2)),
         TD_Def = as.numeric(stringr::str_sub(TD_Def, end = -2))) %>%
  select(-ft, -inch) %>%
  relocate(fighter_name, Height) %>%
  rename("FighterName" = "fighter_name")


```


```{r}
fights_women <- fights %>%
  mutate(sex = ifelse(grepl("Women", weight_class) == TRUE, "Female", "Male")) %>%
  relocate(R_fighter, B_fighter, sex) %>%
  mutate(weight_class = stringr::str_remove(weight_class, "Women"))
```


```{r}
fights_women$sex <- relevel(fights_women$sex, levels = c("Female", "Male"))

# UFC over time

fights_women %>%
  ggplot(aes(x = date, fill = sex)) + geom_histogram(alpha = 0.5, position = "identity") +
  scale_fill_brewer(palette = "Paired") +
  theme_fivethirtyeight() +
  scale_x_date(date_breaks = "5 year", date_labels = "%Y") +
  ggtitle("The Growth of UFC Over Time", subtitle = "Women's Fights Still Trail Far Behind Men's, But Have Increased Significantly In Recent Years")
```


```{r}
rousey <- fights_women %>%
  filter(R_fighter == "Ronda Rousey" | B_fighter == "Ronda Rousey") %>%
  arrange(date) %>%
  mutate(rousey_won = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE),
         fight = 1:8) %>%
  relocate(R_fighter, B_fighter, rousey_won, fight)

```


Ronda Rousey

8 fights total, won first 6 then lost to Holly Holm and Amanda Nunes

No data on first fight vs Liz Carmouche, but for other wins, here's stats:

```{r}
# Rousey's Stats

R_data <- rousey %>%
  select(rousey_won, "fight":"B_Weight_lbs", "B_age") %>%
  slice(1:7) %>%
  rename_all(~stringr::str_replace(.,"B_",""))

B_data <- rousey %>%
  select("rousey_won":"weight_class", "R_avg_KD":"R_age", -B_age) %>%
  slice(8) %>%
  rename_all(~stringr::str_replace(.,"R_",""))

rousey_complete <- rbind(R_data, B_data) %>%
  mutate(fighter = rep("Ronda Rousey", 8)) %>%
  relocate(fighter)

# Opponents' Stats

R_data_opp <- rousey %>%
  select(rousey_won, "fight":"B_Weight_lbs", "B_age") %>%
  slice(8) %>%
  rename_all(~stringr::str_replace(.,"B_",""))

B_data_opp <- rousey %>%
  select("rousey_won":"weight_class", "R_avg_KD":"R_age", -B_age) %>%
  slice(1:7) %>%
  rename_all(~stringr::str_replace(.,"R_",""))

opponents_complete <- rbind(R_data_opp, B_data_opp) %>%
  arrange(fight) %>%
  mutate(fighter = c("Liz Carmouche", "Miesha Tate", "Sara McMann",
                     "Alexis Davis", "Cat Zingano", "Bethe Correa",
                     "Holly Holm", "Amanda Nunes")) %>%
  relocate(fighter)
```

```{r}
rousey_fights <- rbind(rousey_complete,
                       opponents_complete)
```

# Raw data

```{r}
raw_ufc <- read_delim("data/ufc/raw_total_fight_data.csv", delim = ";")
```

```{r}
rousey_raw <- raw_ufc %>% 
  filter(R_fighter == "Ronda Rousey" | B_fighter == "Ronda Rousey")
```

```{r}
rousey_raw$date <- factor(rousey_raw$date, levels = c("February 23, 2013",
                                                      "December 28, 2013",
                                                      "February 22, 2014",
                                                      "July 05, 2014",
                                                      "February 28, 2015",
                                                      "August 01, 2015",
                                                      "November 14, 2015",
                                                      "December 30, 2016"))

rousey_raw <- rousey_raw %>%
  arrange(date) %>%
  mutate(fight_num = 1:8) %>%
  relocate(R_fighter, B_fighter, date, fight_num,
           "win_by":"Winner")

R_data <- rousey_raw %>%
  select("date":"Winner", starts_with("R"), -R_fighter) %>%
  slice(1:7) %>%
  rename_all(~stringr::str_replace(.,"R_",""))

B_data <- rousey_raw %>%
  select("date":"Winner", starts_with("B"), -B_fighter) %>%
  slice(8) %>%
  rename_all(~stringr::str_replace(.,"B_",""))

rousey_complete <- rbind(R_data, B_data) %>%
  mutate(Fighter = "Ronda Rousey") %>%
  relocate(Fighter)

# Opponent's data

R_data <- rousey_raw %>%
  select("date":"Winner", starts_with("R"), -R_fighter) %>%
  slice(8) %>%
  rename_all(~stringr::str_replace(.,"R_",""))

B_data <- rousey_raw %>%
  select("date":"Winner", starts_with("B"), -B_fighter) %>%
  slice(1:7) %>%
  rename_all(~stringr::str_replace(.,"B_",""))

opp_complete <- rbind(B_data, R_data) %>%
  mutate(Fighter = c("Liz Carmouche", "Miesha Tate", "Sara McMann",
                     "Alexis Davis", "Cat Zingano", "Bethe Correa",
                     "Holly Holm", "Amanda Nunes")) %>%
  relocate(Fighter)


rousey_raw_combined <- rbind(rousey_complete, opp_complete)

rousey_cleaned_final <- rousey_raw_combined %>%
  rowwise() %>%
  mutate(SIG_STR_MADE = as.numeric(stringr::str_split(SIG_STR., " of ")[[1]][1]),
         SIG_STR_ATTEMPTED = as.numeric(stringr::str_split(SIG_STR., " of ")[[1]][2]),
         SIG_STR_PROP = round(SIG_STR_MADE/SIG_STR_ATTEMPTED,2),
         TOTAL_STR_MADE = as.numeric(stringr::str_split(TOTAL_STR., " of ")[[1]][1]),
         TOTAL_STR_ATTEMPTED = as.numeric(stringr::str_split(TOTAL_STR., " of ")[[1]][2]),
         TOTAL_STR_PROP = round(TOTAL_STR_MADE/TOTAL_STR_ATTEMPTED, 2),
         TD_MADE = as.numeric(stringr::str_split(TD, " of ")[[1]][1]),
         TD_ATTEMPTED = as.numeric(stringr::str_split(TD, " of ")[[1]][2]),
         TD_PROP = round(TD_MADE/TD_ATTEMPTED, 2),
         HEAD_MADE = as.numeric(stringr::str_split(HEAD, " of ")[[1]][1]),
         HEAD_ATTEMPTED = as.numeric(stringr::str_split(HEAD, " of ")[[1]][2]),
         HEAD_PROP = round(HEAD_MADE/HEAD_ATTEMPTED, 2),
         BODY_MADE = as.numeric(stringr::str_split(BODY, " of ")[[1]][1]),
         BODY_ATTEMPTED = as.numeric(stringr::str_split(BODY, " of ")[[1]][2]),
         BODY_PROP = round(BODY_MADE/BODY_ATTEMPTED, 2),
         LEG_MADE = as.numeric(stringr::str_split(LEG, " of ")[[1]][1]),
         LEG_ATTEMPTED = as.numeric(stringr::str_split(LEG, " of ")[[1]][2]),
         LEG_PROP = round(LEG_MADE/LEG_ATTEMPTED, 2),
         DISTANCE_MADE = as.numeric(stringr::str_split(DISTANCE, " of ")[[1]][1]),
         DISTANCE_ATTEMPTED = as.numeric(stringr::str_split(DISTANCE, " of ")[[1]][2]),
         DISTANCE_PROP = round(DISTANCE_MADE/DISTANCE_ATTEMPTED, 2),
         CLINCH_MADE = as.numeric(stringr::str_split(CLINCH, " of ")[[1]][1]),
         CLINCH_ATTEMPTED = as.numeric(stringr::str_split(CLINCH, " of ")[[1]][2]),
         CLINCH_PROP = round(CLINCH_MADE/CLINCH_ATTEMPTED, 2),
         GROUND_MADE = as.numeric(stringr::str_split(GROUND, " of ")[[1]][1]),
         GROUND_ATTEMPTED = as.numeric(stringr::str_split(GROUND, " of ")[[1]][2]),
         GROUND_PROP = round(GROUND_MADE/GROUND_ATTEMPTED, 2)) %>%
  select("Fighter":"KD", "SIG_STR_MADE":"GROUND_PROP")

```

```{r}
# Clean other data to math Rousey
raw_ufc_women <- raw_ufc %>%
  mutate(sex = ifelse(grepl("Women's", Fight_type) == TRUE, "Female", "Male")) %>%
  filter(sex == "Female")

red_fighters_raw <- raw_ufc_women %>%
  select(starts_with("R_")) %>%
  rename_all(~stringr::str_replace(.,"^R_","")) %>%
  rename("Fighter" = "fighter")

blue_fighters_raw <- raw_ufc_women %>%
  select(starts_with("B_")) %>%
   rename_all(~stringr::str_replace(.,"^B_","")) %>%
  rename("Fighter" = "fighter")

all_fighters_raw_clean <- rbind(red_fighters_raw, blue_fighters_raw) %>%
  rowwise() %>%
  mutate(SIG_STR_MADE = as.numeric(stringr::str_split(SIG_STR., " of ")[[1]][1]),
         SIG_STR_ATTEMPTED = as.numeric(stringr::str_split(SIG_STR., " of ")[[1]][2]),
         SIG_STR_PROP = round(SIG_STR_MADE/SIG_STR_ATTEMPTED,2),
         TOTAL_STR_MADE = as.numeric(stringr::str_split(TOTAL_STR., " of ")[[1]][1]),
         TOTAL_STR_ATTEMPTED = as.numeric(stringr::str_split(TOTAL_STR., " of ")[[1]][2]),
         TOTAL_STR_PROP = round(TOTAL_STR_MADE/TOTAL_STR_ATTEMPTED, 2),
         TD_MADE = as.numeric(stringr::str_split(TD, " of ")[[1]][1]),
         TD_ATTEMPTED = as.numeric(stringr::str_split(TD, " of ")[[1]][2]),
         TD_PROP = round(TD_MADE/TD_ATTEMPTED, 2),
         HEAD_MADE = as.numeric(stringr::str_split(HEAD, " of ")[[1]][1]),
         HEAD_ATTEMPTED = as.numeric(stringr::str_split(HEAD, " of ")[[1]][2]),
         HEAD_PROP = round(HEAD_MADE/HEAD_ATTEMPTED, 2),
         BODY_MADE = as.numeric(stringr::str_split(BODY, " of ")[[1]][1]),
         BODY_ATTEMPTED = as.numeric(stringr::str_split(BODY, " of ")[[1]][2]),
         BODY_PROP = round(BODY_MADE/BODY_ATTEMPTED, 2),
         LEG_MADE = as.numeric(stringr::str_split(LEG, " of ")[[1]][1]),
         LEG_ATTEMPTED = as.numeric(stringr::str_split(LEG, " of ")[[1]][2]),
         LEG_PROP = round(LEG_MADE/LEG_ATTEMPTED, 2),
         DISTANCE_MADE = as.numeric(stringr::str_split(DISTANCE, " of ")[[1]][1]),
         DISTANCE_ATTEMPTED = as.numeric(stringr::str_split(DISTANCE, " of ")[[1]][2]),
         DISTANCE_PROP = round(DISTANCE_MADE/DISTANCE_ATTEMPTED, 2),
         CLINCH_MADE = as.numeric(stringr::str_split(CLINCH, " of ")[[1]][1]),
         CLINCH_ATTEMPTED = as.numeric(stringr::str_split(CLINCH, " of ")[[1]][2]),
         CLINCH_PROP = round(CLINCH_MADE/CLINCH_ATTEMPTED, 2),
         GROUND_MADE = as.numeric(stringr::str_split(GROUND, " of ")[[1]][1]),
         GROUND_ATTEMPTED = as.numeric(stringr::str_split(GROUND, " of ")[[1]][2]),
         GROUND_PROP = round(GROUND_MADE/GROUND_ATTEMPTED, 2)) %>%
  select("Fighter":"KD", "SIG_STR_MADE":"GROUND_PROP")
  
```


```{r}
# CLINCH PROP

# ROUSEY: 
rousey_only <- rousey_cleaned_final %>%
  filter(Fighter == "Ronda Rousey") 

ROUSEY_MEAN_CLINCH_PROP <- mean(rousey_only$CLINCH_PROP, na.rm = TRUE)
ROUSEY_MEAN_SIG_STR_PROP <- mean(rousey_only$SIG_STR_PROP, na.rm = TRUE)
ROUSEY_MEAN_TOTAL_STR_PROP <- mean(rousey_only$TOTAL_STR_PROP, na.rm = TRUE)
ROUSEY_MEAN_TD_PROP <- mean(rousey_only$TD_PROP, na.rm = TRUE)
ROUSEY_MEAN_HEAD_PROP <- mean(rousey_only$HEAD_PROP, na.rm = TRUE)
ROUSEY_MEAN_BODY_PROP <- mean(rousey_only$BODY_PROP, na.rm = TRUE)
ROUSEY_MEAN_LEG_PROP <- mean(rousey_only$LEG_PROP, na.rm = TRUE)
ROUSEY_MEAN_DISTANCE_PROP <- mean(rousey_only$DISTANCE_PROP, na.rm = TRUE)
ROUSEY_MEAN_GROUND_PROP <- mean(rousey_only$GROUND_PROP, na.rm = TRUE)

```


```{r}
# ROUSEY vs OTHER WOMEN in UFC

# SIGNIFICANT STRIKES IN CLINCH

all_fighters_raw_clean %>%
  ggplot(aes(x = CLINCH_PROP)) + 
  geom_histogram(bins = 50) +
  geom_vline(xintercept  = ROUSEY_MEAN_CLINCH_PROP, color = "red") +
  theme_fivethirtyeight() +
  ylab(NULL) +
  theme(axis.text.y= element_blank()) +
  ggtitle("Significant Strikes From CLINCH Position")

# SIGNIFICANT STRIKES ON GROUND

all_fighters_raw_clean %>%
  ggplot(aes(x = GROUND_PROP)) + 
  geom_histogram(bins = 50) +
  geom_vline(xintercept  = ROUSEY_MEAN_GROUND_PROP, color = "red") +
  theme_fivethirtyeight() +
  ylab(NULL) +
  theme(axis.text.y= element_blank()) +
  ggtitle("Significant Strikes From GROUND Position")

# SIGNIFICANT STRIkES IN GENERAL

all_fighters_raw_clean %>%
  ggplot(aes(x = SIG_STR_PROP)) + 
  geom_histogram(bins = 50) +
  geom_vline(xintercept  = ROUSEY_MEAN_SIG_STR_PROP, color = "red") +
  theme_fivethirtyeight() +
  ylab(NULL) +
  theme(axis.text.y= element_blank()) +
  ggtitle("Total Significant Strikes")

# TOTAL STRIKES

all_fighters_raw_clean %>%
  ggplot(aes(x = TOTAL_STR_PROP)) + 
  geom_histogram(bins = 50) +
  geom_vline(xintercept  = ROUSEY_MEAN_TOTAL_STR_PROP, color = "red") +
  theme_fivethirtyeight() +
  ylab(NULL) +
  theme(axis.text.y= element_blank()) +
  ggtitle("Total Strikes")


# TAKEDOWNS

all_fighters_raw_clean %>%
  ggplot(aes(x = TD_PROP)) + 
  geom_histogram(bins = 50) +
  geom_vline(xintercept  = ROUSEY_MEAN_TD_PROP, color = "red") +
  theme_fivethirtyeight() +
  ylab(NULL) +
  theme(axis.text.y= element_blank()) +
  ggtitle("Takedowns")

# HEAD SHOTS

all_fighters_raw_clean %>%
  ggplot(aes(x = HEAD_PROP)) + 
  geom_histogram(bins = 50) +
  geom_vline(xintercept  = ROUSEY_MEAN_HEAD_PROP, color = "red") +
  theme_fivethirtyeight() +
  ylab(NULL) +
  theme(axis.text.y= element_blank()) +
  ggtitle("Strikes to the HEAD")

# BODY SHOTS

all_fighters_raw_clean %>%
  ggplot(aes(x = BODY_PROP)) + 
  geom_histogram(bins = 50) +
  geom_vline(xintercept  = ROUSEY_MEAN_BODY_PROP, color = "red") +
  theme_fivethirtyeight() +
  ylab(NULL) +
  theme(axis.text.y= element_blank()) +
  ggtitle("Strikes to the BODY")

# LEG SHOTS

all_fighters_raw_clean %>%
  ggplot(aes(x = LEG_PROP)) + 
  geom_histogram(bins = 50) +
  geom_vline(xintercept  = ROUSEY_MEAN_LEG_PROP, color = "red") +
  theme_fivethirtyeight() +
  ylab(NULL) +
  theme(axis.text.y= element_blank()) +
  ggtitle("Strikes to the LEG")

# DISTANCE SHOTS

all_fighters_raw_clean %>%
  ggplot(aes(x = DISTANCE_PROP)) + 
  geom_histogram(bins = 50) +
  geom_vline(xintercept  = ROUSEY_MEAN_DISTANCE_PROP, color = "red") +
  theme_fivethirtyeight() +
  ylab(NULL) +
  theme(axis.text.y= element_blank()) +
  ggtitle("Strikes from Distance")

```

